# Generated by Django 5.0.6 on 2024-06-20 03:00

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("COURIER", "courier"),
                            ("RESTRAUNT", "restraunt"),
                            ("CLIENT", "client"),
                        ],
                        default="CLIENT",
                        max_length=10,
                    ),
                ),
                ("is_courier", models.BooleanField(default=False)),
                ("is_restraunt", models.BooleanField(default=False)),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\+[254]\\d{10,11})?$"
                            )
                        ],
                        verbose_name="Telephone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Courier",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=245)),
                ("last_name", models.CharField(max_length=245)),
                (
                    "gender",
                    models.CharField(
                        choices=[("ml", "Male"), ("fl", "Female")],
                        default="ml",
                        max_length=2,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to=accounts.models.img_uploader
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=245, null=True)),
                ("address", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "ordering": ["-id"],
            },
        ),
    ]
